<header>
	<ul>
		<li>
			<a>Inventário</a>
			<div>
				<a>Aa</a>
				<a>Bb</a>
			</div>
		</li>
		<li><a>Encomendas</a></li>
		<li><a>logo</a></li>
		<li><a>Contactos</a></li>
		<li><a>Notas</a></li>
		<li><a>Lembretes</a></li>
	</ul>
</header>